### ISSUE TITLE
Style section in Top menu/ and blog within website

### ISSUE THREAD

**Issue by oliverproudlock** [proudlock/op-website#8]
Want to add Style to top menu and this to take you to proudlockstyle blog within oliverproudlock.com

then the image of style to link to this too as opposed to proudlockstyle.com as it currently does.

In terms of layout of blog want to have as is my proudlockstyle currently. Then underneath the main image, and the 4 detail images below, want to have the products like in my carousel, and clickable to buy ( so if you click will take you to that product on the website it is from in another tab)

Then under that i will write some blur re the outfit.

**Comment by harrygr** [comment]
- [x] Grid of images for style index page. 
- [x] Masonry for single post page
- [x] Import old posts from tumblr
